namespace Epsilon.Core.Research;

public static class LeanExporter
{
    public static string ExportLeanProject(string markdownContent, string title, string outputDir)
    {
        Directory.CreateDirectory(outputDir);

        var safeTitle = string.Join("_",
            title.Split(Path.GetInvalidFileNameChars(),
            StringSplitOptions.RemoveEmptyEntries)).Trim();

        if (safeTitle.Length > 60) safeTitle = safeTitle[..60];
        if (string.IsNullOrWhiteSpace(safeTitle)) safeTitle = "lean_proof";

        var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
        var fileName = $"{safeTitle}_{timestamp}.lean";
        var filePath = Path.Combine(outputDir, fileName);

        // Extract lean code blocks from the markdown
        var leanCode = ExtractLeanCode(markdownContent, title);

        File.WriteAllText(filePath, leanCode, System.Text.Encoding.UTF8);

        // Also write a lakefile.lean in the same directory (if it doesn't exist)
        var lakefilePath = Path.Combine(outputDir, "lakefile.lean");
        if (!File.Exists(lakefilePath))
        {
            File.WriteAllText(lakefilePath, GetLakefile(safeTitle), System.Text.Encoding.UTF8);
        }

        return filePath;
    }

    private static string ExtractLeanCode(string markdown, string title)
    {
        var sb = new System.Text.StringBuilder();

        sb.AppendLine($"-- {title}");
        sb.AppendLine($"-- Generated by Epsilon on {DateTime.Now:yyyy-MM-dd}");
        sb.AppendLine("-- Requires Mathlib (see lakefile.lean)");
        sb.AppendLine();
        sb.AppendLine("import Mathlib");
        sb.AppendLine();

        // Extract all ```lean ... ``` blocks
        var regex = new System.Text.RegularExpressions.Regex(
            @"```lean\s*\n(.*?)```",
            System.Text.RegularExpressions.RegexOptions.Singleline |
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);

        var matches = regex.Matches(markdown);

        if (matches.Count > 0)
        {
            foreach (System.Text.RegularExpressions.Match match in matches)
            {
                var code = match.Groups[1].Value.Trim();
                // Skip import lines if already added
                var filteredLines = code.Split('\n')
                    .Where(l => !l.TrimStart().StartsWith("import "))
                    .ToList();
                sb.AppendLine(string.Join('\n', filteredLines));
                sb.AppendLine();
            }
        }
        else
        {
            // No lean blocks found — emit a placeholder
            sb.AppendLine("-- No Lean 4 code blocks were found in the generated content.");
            sb.AppendLine("-- Run the LeanBridge tool and generate the Lean Translation step.");
            sb.AppendLine();
            sb.AppendLine("-- Example theorem (replace with your own):");
            sb.AppendLine("theorem example_theorem : True := trivial");
        }

        return sb.ToString();
    }

    private static string GetLakefile(string projectName)
    {
        return $"""
import Lake
open Lake DSL

package «{projectName}» where
  -- add package configuration options here

require mathlib from git
  "https://github.com/leanprover-community/mathlib4"

@[default_target]
lean_lib «{projectName}» where
  -- add library configuration options here
""";
    }
}
