using Epsilon.Core.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Epsilon.Core.Research;

public static class ResearchPdfExporter
{
    static ResearchPdfExporter()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static string Export(ResearchProject project, List<ResearchStep> steps,
        ToolDefinition tool, string outputDir)
    {
        var safeTitle = string.Join("_",
            project.Title.Split(Path.GetInvalidFileNameChars(),
            StringSplitOptions.RemoveEmptyEntries)).Trim();

        if (safeTitle.Length > 60) safeTitle = safeTitle[..60];
        if (string.IsNullOrWhiteSpace(safeTitle)) safeTitle = "research_project";

        var fileName = $"{safeTitle}_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";
        var filePath = Path.Combine(outputDir, fileName);

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Black));

                // Header
                page.Header().Column(col =>
                {
                    col.Item().Text(project.Title)
                        .FontSize(22).Bold().FontColor(Colors.Blue.Darken2);

                    col.Item().PaddingTop(4).Text(text =>
                    {
                        text.Span("Tool: ").SemiBold();
                        text.Span(tool.DisplayName);
                        text.Span("  |  ");
                        text.Span("Created: ").SemiBold();
                        text.Span(project.CreatedAt.ToString("yyyy-MM-dd"));
                    });

                    col.Item().PaddingTop(8)
                        .LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                // Content
                page.Content().PaddingTop(16).Column(col =>
                {
                    foreach (var stepDef in tool.Steps)
                    {
                        var step = steps.FirstOrDefault(s => s.StepIndex == stepDef.Index);
                        var content = step?.GeneratedContent;
                        var hasContent = !string.IsNullOrWhiteSpace(content);

                        col.Item().PaddingTop(16).Text(stepDef.Label)
                            .FontSize(16).Bold().FontColor(Colors.Blue.Darken1);

                        if (hasContent)
                        {
                            // Render plain text (LaTeX won't render in PDF but formulas are still readable)
                            col.Item().PaddingTop(6).Text(content!)
                                .FontSize(11).LineHeight(1.5f);
                        }
                        else
                        {
                            col.Item().PaddingTop(6).Text("(Section not completed)")
                                .FontSize(11).Italic().FontColor(Colors.Grey.Medium);
                        }

                        col.Item().PaddingTop(12)
                            .LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten3);
                    }
                });

                // Footer
                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Epsilon — ");
                    text.CurrentPageNumber();
                    text.Span(" / ");
                    text.TotalPages();
                });
            });
        }).GeneratePdf(filePath);

        return filePath;
    }
}
