using System.Text.RegularExpressions;
using Epsilon.Core.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Epsilon.Core.Research;

public static class ResearchPdfExporter
{
    static ResearchPdfExporter()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static string Export(ResearchProject project, List<ResearchStep> steps,
        ToolDefinition tool, string outputDir)
    {
        var safeTitle = string.Join("_",
            project.Title.Split(Path.GetInvalidFileNameChars(),
            StringSplitOptions.RemoveEmptyEntries)).Trim();

        if (safeTitle.Length > 60) safeTitle = safeTitle[..60];
        if (string.IsNullOrWhiteSpace(safeTitle)) safeTitle = "research_project";

        var fileName = $"{safeTitle}_{DateTime.Now:yyyyMMdd_HHmmss}.pdf";
        var filePath = Path.Combine(outputDir, fileName);

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11).FontColor(Colors.Black));

                page.Header().Column(col =>
                {
                    col.Item().Text(project.Title)
                        .FontSize(22).Bold().FontColor(Colors.Blue.Darken2);

                    col.Item().PaddingTop(4).Text(text =>
                    {
                        text.Span("Tool: ").SemiBold();
                        text.Span(tool.DisplayName);
                        text.Span("  |  ");
                        text.Span("Created: ").SemiBold();
                        text.Span(project.CreatedAt.ToString("yyyy-MM-dd"));
                    });

                    col.Item().PaddingTop(8)
                        .LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                });

                page.Content().PaddingTop(16).Column(col =>
                {
                    foreach (var stepDef in tool.Steps)
                    {
                        var step = steps.FirstOrDefault(s => s.StepIndex == stepDef.Index);
                        var rawContent = step?.GeneratedContent;
                        var hasContent = !string.IsNullOrWhiteSpace(rawContent);

                        col.Item().PaddingTop(16).Text(stepDef.Label)
                            .FontSize(16).Bold().FontColor(Colors.Blue.Darken1);

                        if (hasContent)
                        {
                            var rendered = LatexToUnicode.Convert(rawContent!);
                            col.Item().PaddingTop(6).Text(rendered)
                                .FontSize(11).LineHeight(1.5f);
                        }
                        else
                        {
                            col.Item().PaddingTop(6).Text("(Section not completed)")
                                .FontSize(11).Italic().FontColor(Colors.Grey.Medium);
                        }

                        col.Item().PaddingTop(12)
                            .LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten3);
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Epsilon — ");
                    text.CurrentPageNumber();
                    text.Span(" / ");
                    text.TotalPages();
                });
            });
        }).GeneratePdf(filePath);

        return filePath;
    }
}

/// <summary>
/// Converts LaTeX + Markdown content to readable Unicode text for PDF rendering.
/// Processing order is critical — structural commands first, then symbols, then cleanup.
/// </summary>
internal static class LatexToUnicode
{
    public static string Convert(string content)
    {
        var text = content;

        // ── Phase 1: Strip Markdown formatting ──
        text = Regex.Replace(text, @"\*\*\*(.+?)\*\*\*", "$1");
        text = Regex.Replace(text, @"\*\*(.+?)\*\*", "$1");
        text = Regex.Replace(text, @"(?<!\w)\*(.+?)\*(?!\w)", "$1");
        text = Regex.Replace(text, @"__(.+?)__", "$1");
        text = Regex.Replace(text, @"^#{1,6}\s+", "", RegexOptions.Multiline);
        text = Regex.Replace(text, @"```\w*\n?", "");
        text = Regex.Replace(text, @"`([^`]+)`", "$1");

        // ── Phase 2: Handle math delimiters ──
        // Process display math $$...$$ first (greedy inner)
        text = Regex.Replace(text, @"\$\$(.*?)\$\$", m => ProcessLatex(m.Groups[1].Value), RegexOptions.Singleline);
        // Then inline math $...$
        text = Regex.Replace(text, @"(?<!\$)\$(?!\$)(.+?)\$(?!\$)", m => ProcessLatex(m.Groups[1].Value));

        // ── Phase 3: Convert any remaining LaTeX outside delimiters ──
        text = ProcessLatex(text);

        // ── Phase 4: Final cleanup ──
        text = Regex.Replace(text, @"\n{3,}", "\n\n");
        text = Regex.Replace(text, @"[ \t]+\n", "\n");
        text = Regex.Replace(text, @"  +", " ");

        return text.Trim();
    }

    private static string ProcessLatex(string latex)
    {
        var t = latex;

        // ── Step 1: Escaped braces (before anything else) ──
        t = t.Replace("\\{", "⟮").Replace("\\}", "⟯");  // temp placeholders
        t = t.Replace("\\\\", "\n");  // line breaks

        // ── Step 2: Strip display/style commands ──
        t = t.Replace("\\displaystyle", "").Replace("\\textstyle", "");
        t = t.Replace("\\limits", "").Replace("\\nolimits", "");
        t = t.Replace("\\nonumber", "").Replace("\\notag", "");
        t = t.Replace("\\label{", "{"); // strip labels

        // ── Step 3: Structural commands with arguments (recursive-safe) ──

        // \sqrt[n]{x} → ⁿ√(x)
        t = Regex.Replace(t, @"\\sqrt\[([^\]]*)\]\{([^}]*)\}", m =>
            ToSuperscript(m.Groups[1].Value) + "√(" + m.Groups[2].Value + ")");
        // \sqrt{x} → √(x)
        t = Regex.Replace(t, @"\\sqrt\{([^}]*)\}", "√($1)");
        t = t.Replace("\\sqrt", "√");

        // ── Derivative fractions (BEFORE general \frac) ──

        // \frac{\partial^2 f}{\partial x \partial y} → ∂²f/∂x∂y
        t = Regex.Replace(t, @"\\(?:d?frac|tfrac|cfrac)\{\\partial\^?\{?(\w*)\}?\s*([^}]*)\}\{\\partial\s+([^}]*)\}", m =>
        {
            var order = m.Groups[1].Value;
            var func = m.Groups[2].Value.Trim();
            var vars = m.Groups[3].Value.Trim();
            // Convert \partial to ∂ in denominator
            vars = vars.Replace("\\partial", "∂");
            var orderStr = string.IsNullOrEmpty(order) ? "" : ToSuperscript(order);
            return $"∂{orderStr}{func}/∂{vars}";
        });

        // \frac{d^2 f}{dx^2} → d²f/dx²
        t = Regex.Replace(t, @"\\(?:d?frac|tfrac|cfrac)\{d\^?\{?(\w*)\}?\s*([^}]*)\}\{d([^}]*)\}", m =>
        {
            var order = m.Groups[1].Value;
            var func = m.Groups[2].Value.Trim();
            var vars = m.Groups[3].Value.Trim();
            var orderStr = string.IsNullOrEmpty(order) ? "" : ToSuperscript(order);
            return $"d{orderStr}{func}/d{vars}";
        });

        // \frac{a}{b} → a/b (smart parens only when needed)
        t = Regex.Replace(t, @"\\(?:d?frac|tfrac|cfrac)\{([^}]*)\}\{([^}]*)\}", m =>
        {
            var num = m.Groups[1].Value.Trim();
            var den = m.Groups[2].Value.Trim();
            // Simple numerator/denominator: no parens needed
            bool numSimple = num.Length <= 5 && !num.Contains(' ') && !num.Contains('+') && !num.Contains('-');
            bool denSimple = den.Length <= 5 && !den.Contains(' ') && !den.Contains('+') && !den.Contains('-');
            if (numSimple && denSimple)
                return $"{num}/{den}";
            var n = numSimple ? num : $"({num})";
            var d = denSimple ? den : $"({den})";
            return $"{n}/{d}";
        });

        // \binom{n}{k} → C(n,k)
        t = Regex.Replace(t, @"\\binom\{([^}]*)\}\{([^}]*)\}", "C($1,$2)");
        t = Regex.Replace(t, @"\\choose\b", ","); // old TeX {n \choose k}

        // \boxed{...} → ⟦...⟧
        t = Regex.Replace(t, @"\\boxed\{([^}]*)\}", "⟦ $1 ⟧");

        // \text{...}, \mathrm{...} etc → content
        t = Regex.Replace(t, @"\\(?:text|textrm|textbf|textit|textsc|textsf|texttt)\{([^}]*)\}", "$1");
        t = Regex.Replace(t, @"\\(?:mathrm|mathbf|mathit|mathsf|mathtt|mathcal|mathscr|mathfrak|mathbb)\{([^}]*)\}", m =>
            ConvertMathbb(m.Value, m.Groups[1].Value));

        // \overline{x} → x̄  (combining overline)
        t = Regex.Replace(t, @"\\overline\{([^}]*)\}", "$1\u0304");
        t = Regex.Replace(t, @"\\bar\{([^}]*)\}", "$1\u0304");
        t = Regex.Replace(t, @"\\underline\{([^}]*)\}", "$1");
        t = Regex.Replace(t, @"\\hat\{([^}]*)\}", "$1\u0302");
        t = Regex.Replace(t, @"\\tilde\{([^}]*)\}", "$1\u0303");
        t = Regex.Replace(t, @"\\vec\{([^}]*)\}", "$1\u20D7");
        t = Regex.Replace(t, @"\\dot\{([^}]*)\}", "$1\u0307");
        t = Regex.Replace(t, @"\\ddot\{([^}]*)\}", "$1\u0308");
        t = Regex.Replace(t, @"\\(?:widetilde|widehat|acute|grave|breve|check)\{([^}]*)\}", "$1");
        t = Regex.Replace(t, @"\\(?:underbrace|overbrace)\{([^}]*)\}", "$1");
        t = Regex.Replace(t, @"\\(?:stackrel|overset|underset)\{([^}]*)\}\{([^}]*)\}", "$2");
        t = Regex.Replace(t, @"\\operatorname\{([^}]*)\}", "$1");
        t = Regex.Replace(t, @"\\(?:color|textcolor)\{[^}]*\}\{([^}]*)\}", "$1");

        // \left \right delimiters
        t = t.Replace("\\left(", "(").Replace("\\right)", ")");
        t = t.Replace("\\left[", "[").Replace("\\right]", "]");
        t = t.Replace("\\left\\{", "{").Replace("\\right\\}", "}");
        t = t.Replace("\\left|", "|").Replace("\\right|", "|");
        t = t.Replace("\\left\\|", "‖").Replace("\\right\\|", "‖");
        t = t.Replace("\\left.", "").Replace("\\right.", "");
        t = t.Replace("\\big(", "(").Replace("\\big)", ")");
        t = t.Replace("\\Big(", "(").Replace("\\Big)", ")");
        t = t.Replace("\\bigg(", "(").Replace("\\bigg)", ")");
        t = t.Replace("\\Bigg(", "(").Replace("\\Bigg)", ")");
        t = Regex.Replace(t, @"\\(?:big|Big|bigg|Bigg|left|right)\s*", "");

        // Environments
        t = Regex.Replace(t, @"\\begin\{(?:align|aligned|equation|gather|cases|array|matrix|pmatrix|bmatrix|vmatrix|smallmatrix)\*?\}", "");
        t = Regex.Replace(t, @"\\end\{(?:align|aligned|equation|gather|cases|array|matrix|pmatrix|bmatrix|vmatrix|smallmatrix)\*?\}", "");

        // ── Step 4: Greek letters (LONGER NAMES FIRST to prevent partial matches) ──

        // Lowercase variants first (longer)
        t = t.Replace("\\varepsilon", "ε").Replace("\\vartheta", "ϑ").Replace("\\varpi", "ϖ");
        t = t.Replace("\\varrho", "ϱ").Replace("\\varsigma", "ς").Replace("\\varphi", "φ");

        // Uppercase
        t = t.Replace("\\Gamma", "Γ").Replace("\\Delta", "Δ").Replace("\\Theta", "Θ");
        t = t.Replace("\\Lambda", "Λ").Replace("\\Xi", "Ξ").Replace("\\Pi", "Π");
        t = t.Replace("\\Sigma", "Σ").Replace("\\Upsilon", "Υ").Replace("\\Phi", "Φ");
        t = t.Replace("\\Psi", "Ψ").Replace("\\Omega", "Ω");

        // Lowercase (alphabetical, after variants)
        t = t.Replace("\\alpha", "α").Replace("\\beta", "β").Replace("\\gamma", "γ");
        t = t.Replace("\\delta", "δ").Replace("\\epsilon", "ε").Replace("\\zeta", "ζ");
        t = t.Replace("\\eta", "η").Replace("\\theta", "θ").Replace("\\iota", "ι");
        t = t.Replace("\\kappa", "κ").Replace("\\lambda", "λ").Replace("\\mu", "μ");
        t = t.Replace("\\nu", "ν").Replace("\\xi", "ξ").Replace("\\pi", "π");
        t = t.Replace("\\rho", "ρ").Replace("\\sigma", "σ").Replace("\\tau", "τ");
        t = t.Replace("\\upsilon", "υ").Replace("\\phi", "ϕ").Replace("\\chi", "χ");
        t = t.Replace("\\psi", "ψ").Replace("\\omega", "ω").Replace("\\ell", "ℓ");

        // ── Step 5: Operators (LONGER FIRST) ──
        t = t.Replace("\\implies", " ⟹ ").Replace("\\impliedby", " ⟸ ");
        t = t.Replace("\\Leftrightarrow", " ⇔ ").Replace("\\Longleftrightarrow", " ⟺ ");
        t = t.Replace("\\Rightarrow", " ⇒ ").Replace("\\Leftarrow", " ⇐ ");
        t = t.Replace("\\longrightarrow", " ⟶ ").Replace("\\longleftarrow", " ⟵ ");
        t = t.Replace("\\leftrightarrow", " ↔ ");
        t = t.Replace("\\rightarrow", " → ").Replace("\\leftarrow", " ← ");
        t = t.Replace("\\hookrightarrow", " ↪ ").Replace("\\hookleftarrow", " ↩ ");
        t = t.Replace("\\nearrow", "↗").Replace("\\searrow", "↘");
        t = t.Replace("\\nwarrow", "↖").Replace("\\swarrow", "↙");
        t = t.Replace("\\uparrow", "↑").Replace("\\downarrow", "↓");
        t = t.Replace("\\Uparrow", "⇑").Replace("\\Downarrow", "⇓");
        t = t.Replace("\\mapsto", " ↦ ").Replace("\\longmapsto", " ⟼ ");
        t = t.Replace("\\iff", " ⟺ ").Replace("\\to", " → ").Replace("\\gets", " ← ");

        // Relations (longer first)
        t = t.Replace("\\subseteq", "⊆").Replace("\\supseteq", "⊇");
        t = t.Replace("\\subsetneq", "⊊").Replace("\\supsetneq", "⊋");
        t = t.Replace("\\subset", "⊂").Replace("\\supset", "⊃");
        t = t.Replace("\\notin", "∉").Replace("\\not\\in", "∉");
        t = t.Replace("\\approx", "≈").Replace("\\equiv", "≡").Replace("\\cong", "≅");
        t = t.Replace("\\simeq", "≃").Replace("\\sim", "∼").Replace("\\propto", "∝");
        t = t.Replace("\\preceq", "≼").Replace("\\succeq", "≽");
        t = t.Replace("\\prec", "≺").Replace("\\succ", "≻");
        t = t.Replace("\\leq", "≤").Replace("\\geq", "≥").Replace("\\neq", "≠");
        t = t.Replace("\\le", "≤").Replace("\\ge", "≥").Replace("\\ne", "≠");
        t = t.Replace("\\ll", "≪").Replace("\\gg", "≫");
        t = t.Replace("\\in", "∈").Replace("\\ni", "∋");
        t = t.Replace("\\mid", " | ").Replace("\\nmid", "∤");
        t = t.Replace("\\perp", "⊥").Replace("\\parallel", "∥");
        t = t.Replace("\\vdash", "⊢").Replace("\\dashv", "⊣").Replace("\\models", "⊨");

        // Binary operators
        t = t.Replace("\\times", "×").Replace("\\div", "÷").Replace("\\cdot", "·");
        t = t.Replace("\\pm", "±").Replace("\\mp", "∓").Replace("\\circ", "∘");
        t = t.Replace("\\oplus", "⊕").Replace("\\otimes", "⊗").Replace("\\odot", "⊙");
        t = t.Replace("\\ominus", "⊖").Replace("\\oslash", "⊘");
        t = t.Replace("\\cap", "∩").Replace("\\cup", "∪");
        t = t.Replace("\\sqcap", "⊓").Replace("\\sqcup", "⊔");
        t = t.Replace("\\vee", "∨").Replace("\\wedge", "∧");
        t = t.Replace("\\setminus", "∖").Replace("\\smallsetminus", "∖");
        t = t.Replace("\\star", "⋆").Replace("\\ast", "∗");
        t = t.Replace("\\bullet", "•").Replace("\\diamond", "◇");
        t = t.Replace("\\triangleleft", "◁").Replace("\\triangleright", "▷");
        t = t.Replace("\\lhd", "⊲").Replace("\\rhd", "⊳");

        // Quantifiers and logic
        t = t.Replace("\\forall", "∀").Replace("\\exists", "∃").Replace("\\nexists", "∄");
        t = t.Replace("\\land", "∧").Replace("\\lor", "∨").Replace("\\lnot", "¬").Replace("\\neg", "¬");
        t = t.Replace("\\top", "⊤").Replace("\\bot", "⊥");

        // Big operators
        t = t.Replace("\\bigcup", "⋃").Replace("\\bigcap", "⋂");
        t = t.Replace("\\bigoplus", "⨁").Replace("\\bigotimes", "⨂");
        t = t.Replace("\\bigvee", "⋁").Replace("\\bigwedge", "⋀");
        t = t.Replace("\\bigsqcup", "⨆");
        t = t.Replace("\\coprod", "∐");
        t = t.Replace("\\iiint", "∭").Replace("\\iint", "∬");
        t = t.Replace("\\oint", "∮").Replace("\\int", "∫");
        t = t.Replace("\\sum", "∑").Replace("\\prod", "∏");

        // Calculus — partial and nabla with superscripts
        t = Regex.Replace(t, @"\\partial\^\{([^}]*)\}", m => "∂" + ToSuperscript(m.Groups[1].Value));
        t = Regex.Replace(t, @"\\partial\^(\w)", m => "∂" + ToSuperscript(m.Groups[1].Value));
        t = Regex.Replace(t, @"\\nabla\^\{([^}]*)\}", m => "∇" + ToSuperscript(m.Groups[1].Value));
        t = Regex.Replace(t, @"\\nabla\^(\w)", m => "∇" + ToSuperscript(m.Groups[1].Value));

        // Misc symbols
        t = t.Replace("\\infty", "∞").Replace("\\partial", "∂").Replace("\\nabla", "∇");
        t = t.Replace("\\emptyset", "∅").Replace("\\varnothing", "∅");
        t = t.Replace("\\triangle", "△").Replace("\\angle", "∠");
        t = t.Replace("\\measuredangle", "∡").Replace("\\sphericalangle", "∢");
        t = t.Replace("\\langle", "⟨").Replace("\\rangle", "⟩");
        t = t.Replace("\\lceil", "⌈").Replace("\\rceil", "⌉");
        t = t.Replace("\\lfloor", "⌊").Replace("\\rfloor", "⌋");
        t = t.Replace("\\ldots", "…").Replace("\\cdots", "⋯").Replace("\\dots", "…");
        t = t.Replace("\\vdots", "⋮").Replace("\\ddots", "⋱");
        t = t.Replace("\\therefore", "∴").Replace("\\because", "∵");
        t = t.Replace("\\prime", "′").Replace("\\backprime", "‵");
        t = t.Replace("\\degree", "°").Replace("\\circ", "°");
        t = t.Replace("\\hbar", "ℏ").Replace("\\Re", "ℜ").Replace("\\Im", "ℑ");
        t = t.Replace("\\wp", "℘").Replace("\\aleph", "ℵ");
        t = t.Replace("\\dagger", "†").Replace("\\ddagger", "‡");
        t = t.Replace("\\checkmark", "✓");
        t = t.Replace("\\blacksquare", "■").Replace("\\square", "□");
        t = t.Replace("\\qed", "∎").Replace("\\QED", "∎");

        // Number sets (\mathbb handled above, but catch plain versions)
        t = t.Replace("\\R", "ℝ").Replace("\\N", "ℕ").Replace("\\Z", "ℤ");
        t = t.Replace("\\Q", "ℚ").Replace("\\C", "ℂ");

        // Function names
        foreach (var fn in new[] { "sin", "cos", "tan", "cot", "sec", "csc",
            "arcsin", "arccos", "arctan", "sinh", "cosh", "tanh",
            "log", "ln", "exp", "lim", "sup", "inf", "max", "min",
            "det", "dim", "ker", "gcd", "lcm", "deg", "hom", "arg",
            "Pr", "tr", "rank", "sgn", "mod" })
        {
            t = t.Replace($"\\{fn}", fn);
        }
        t = Regex.Replace(t, @"\\operatorname\*?\{([^}]*)\}", "$1");

        // ── Step 6: Superscripts and subscripts ──
        // Handle ^{...} with full Unicode mapping
        t = Regex.Replace(t, @"\^\{([^}]*)\}", m => ToSuperscript(m.Groups[1].Value));
        // Handle ^x (single char)
        t = Regex.Replace(t, @"\^([0-9a-zA-Z+\-=\(\)])", m => ToSuperscript(m.Groups[1].Value));

        // Handle _{...}
        t = Regex.Replace(t, @"_\{([^}]*)\}", m => ToSubscript(m.Groups[1].Value));
        // Handle _x (single char)
        t = Regex.Replace(t, @"_([0-9a-zA-Z])", m => ToSubscript(m.Groups[1].Value));

        // ── Step 7: Spacing commands ──
        t = t.Replace("\\qquad", "    ").Replace("\\quad", "  ");
        t = t.Replace("\\;", " ").Replace("\\:", " ").Replace("\\,", " ").Replace("\\!", "");
        t = t.Replace("\\hspace{1em}", " ").Replace("\\hfill", "  ");
        t = t.Replace("\\enspace", " ").Replace("\\thinspace", " ");

        // Alignment markers from environments
        t = t.Replace("&=", " = ").Replace("&\\leq", " ≤ ").Replace("&\\geq", " ≥ ");
        t = t.Replace("&<", " < ").Replace("&>", " > ");
        t = t.Replace("& ", " ").Replace("&", " ");

        // ── Step 8: Restore escaped braces and clean up ──
        t = t.Replace("⟮", "{").Replace("⟯", "}");

        // Strip remaining curly braces (LaTeX grouping)
        t = t.Replace("{", "").Replace("}", "");

        // Clean up any remaining unknown \commands (keep the name, drop the backslash)
        t = Regex.Replace(t, @"\\([a-zA-Z]+)", "$1");

        return t;
    }

    private static string ConvertMathbb(string full, string content)
    {
        var map = new Dictionary<string, string>
        {
            ["R"] = "ℝ", ["N"] = "ℕ", ["Z"] = "ℤ", ["Q"] = "ℚ", ["C"] = "ℂ",
            ["P"] = "ℙ", ["F"] = "𝔽", ["H"] = "ℍ", ["A"] = "𝔸", ["B"] = "𝔹",
            ["D"] = "𝔻", ["E"] = "𝔼", ["G"] = "𝔾", ["I"] = "𝕀", ["J"] = "𝕁",
            ["K"] = "𝕂", ["L"] = "𝕃", ["M"] = "𝕄", ["O"] = "𝕆", ["S"] = "𝕊",
            ["T"] = "𝕋", ["U"] = "𝕌", ["V"] = "𝕍", ["W"] = "𝕎", ["X"] = "𝕏",
            ["Y"] = "𝕐", ["1"] = "𝟙", ["0"] = "𝟘",
        };

        if (full.Contains("\\mathbb"))
        {
            var result = "";
            foreach (var ch in content)
                result += map.TryGetValue(ch.ToString(), out var u) ? u : ch.ToString();
            return result;
        }
        // Other \math... commands: just return content
        return content;
    }

    private static readonly Dictionary<char, char> SuperscriptMap = new()
    {
        ['0'] = '⁰', ['1'] = '¹', ['2'] = '²', ['3'] = '³', ['4'] = '⁴',
        ['5'] = '⁵', ['6'] = '⁶', ['7'] = '⁷', ['8'] = '⁸', ['9'] = '⁹',
        ['+'] = '⁺', ['-'] = '⁻', ['='] = '⁼', ['('] = '⁽', [')'] = '⁾',
        ['a'] = 'ᵃ', ['b'] = 'ᵇ', ['c'] = 'ᶜ', ['d'] = 'ᵈ', ['e'] = 'ᵉ',
        ['f'] = 'ᶠ', ['g'] = 'ᵍ', ['h'] = 'ʰ', ['i'] = 'ⁱ', ['j'] = 'ʲ',
        ['k'] = 'ᵏ', ['l'] = 'ˡ', ['m'] = 'ᵐ', ['n'] = 'ⁿ', ['o'] = 'ᵒ',
        ['p'] = 'ᵖ', ['r'] = 'ʳ', ['s'] = 'ˢ', ['t'] = 'ᵗ', ['u'] = 'ᵘ',
        ['v'] = 'ᵛ', ['w'] = 'ʷ', ['x'] = 'ˣ', ['y'] = 'ʸ', ['z'] = 'ᶻ',
        ['T'] = 'ᵀ',
    };

    private static readonly Dictionary<char, char> SubscriptMap = new()
    {
        ['0'] = '₀', ['1'] = '₁', ['2'] = '₂', ['3'] = '₃', ['4'] = '₄',
        ['5'] = '₅', ['6'] = '₆', ['7'] = '₇', ['8'] = '₈', ['9'] = '₉',
        ['+'] = '₊', ['-'] = '₋', ['='] = '₌', ['('] = '₍', [')'] = '₎',
        ['a'] = 'ₐ', ['e'] = 'ₑ', ['h'] = 'ₕ', ['i'] = 'ᵢ', ['j'] = 'ⱼ',
        ['k'] = 'ₖ', ['l'] = 'ₗ', ['m'] = 'ₘ', ['n'] = 'ₙ', ['o'] = 'ₒ',
        ['p'] = 'ₚ', ['r'] = 'ᵣ', ['s'] = 'ₛ', ['t'] = 'ₜ', ['u'] = 'ᵤ',
        ['v'] = 'ᵥ', ['x'] = 'ₓ',
    };

    private static string ToSuperscript(string text)
    {
        var result = "";
        foreach (var ch in text)
            result += SuperscriptMap.TryGetValue(ch, out var sup) ? sup.ToString() : ch.ToString();
        return result;
    }

    private static string ToSubscript(string text)
    {
        var result = "";
        foreach (var ch in text)
            result += SubscriptMap.TryGetValue(ch, out var sub) ? sub.ToString() : ch.ToString();
        return result;
    }
}
